### PR TITLE
add landing page instead of nothing if nilan isnt connected

### PR DESCRIPTION
**Pull request by sveip**
There seems to be some issue with the closing of the http request, not sure how that is handled today. Page might be slow to load, but should work.

### CODE REVIEW

**Comment by jascdk** [comment]
Skærmbillede 2020-02-06 kl  21 57 39

It works - but I don't quite understand the purpose of it - is it supposed to look like this?

**Comment by sveip** [comment]
Correct. It just gives the user some feedback that the unit actually works,
earlier it was a blank page. You can off course make it much more fancy,
but I dont really see the need for that.

tor. 6. feb. 2020 kl. 22:00 skrev jascdk <notifications@github.com>:

**Comment by jascdk** [comment]
But what are your thoughts on the wifimanager library made by tzapu here on GitHub? Im always talking about it, but thinks its pretty nifty piece of code - it makes the coding more complex, but it should be possible to fit inside this code - but I never got it to work.

Here are som screenshots on a test nodemcu running the DEV branch of that wifimanager library.

Gives a lot of info.

Skærmbillede 2020-02-06 kl  22 09 05
Skærmbillede 2020-02-06 kl  22 07 40
Skærmbillede 2020-02-06 kl  22 07 15

**Comment by jascdk** [comment]
Also supports a way to input Mqtt credentials - together with wifi credentials - that way the config file would be unnecessary. Just a thought - but I need some help to make it :D

**Comment by sveip** [comment]
Im sure it's possible as long as there is enough space on the flash, but I
dont have the time to make something that involved Im afraid.

tor. 6. feb. 2020 kl. 22:17 skrev jascdk <notifications@github.com>:

**Pull request merged**
