### PR TITLE
Revert "add landing page instead of nothing if nilan isnt connected"

### PR DESCRIPTION
**Pull request by jascdk**
Reverts jascdk/Nilan_Homeassistant#15

@sveip Hi:) Would it be possible to add the landing page with a define, so the user is able to add or disable it? It removes the old json, which the system were capable of showing before.

I think I will try to revert it for now

### CODE REVIEW

**Comment by sveip** [comment]
There is a check if json is present, and in that case it should be as
before. But probably a bug in the check if you don't get any json.

Peter

**Comment by jascdk** [comment]
> There is a check if json is present, and in that case it should be as before. But probably a bug in the check if you don't get any json. Peter
> […](#)

Do you get some json response on your system?

**Comment by sveip** [comment]
I dont have it connected yet to my Nilan, so I havent been able to test it with real data. I added a comment to my PR, with some explanation, if you want you can test that and maybe post the results? Also if you would just post the JSON result you typically get when accessing the index html, that would be useful.

**Comment by jascdk** [comment]
As it is now I get something like this when accessing http://10.0.1.16/help and http://10.0.1.16/read/control (like an example) 
Skærmbillede 2020-02-16 kl  13 51 29
Skærmbillede 2020-02-16 kl  13 51 06

**Comment by sveip** [comment]
What do you get from  http://10.0.1.16/ <http://10.0.1.16/help> ?

søn. 16. feb. 2020 kl. 13:53 skrev jascdk <notifications@github.com>:

**Comment by sveip** [comment]
If you want, you can test this version:
https://github.com/sveip/Nilan_Homeassistant/blob/master/nilan_code/nilan_code.ino

It should hopefully give the info page when nothing is present in the json,
and the json itself it if is.

søn. 16. feb. 2020 kl. 14:26 skrev Peter Sveistrup <petersveistrup@gmail.com

**Comment by jascdk** [comment]
http://10.0.1.16/ gives nothing else than this: 
Skærmbillede 2020-02-16 kl  16 33 04

http://10.0.1.16/help gives the same as before

**Comment by sveip** [comment]
it seems "group" is always there, so my latest commit should then in theory
work.

søn. 16. feb. 2020 kl. 16:33 skrev jascdk <notifications@github.com>:

**Comment by jascdk** [comment]
When are you getting your system up and running? It would be nice to know what you see at your system:)

**Comment by sveip** [comment]
It depends, the front panel on my Nilan Compact S is really stuck on there,
so not sure how I'll be able to access the board for the modbus.


man. 17. feb. 2020 kl. 16:46 skrev jascdk <notifications@github.com>:

**Comment by jascdk** [comment]
okay - instead of using the HTML page i thought of taking the given values out via json format, so the wifi connected / not connected - Ip-Address, Mqtt connected / not connected and so forth would be able to read in json format ? I could maybe make a "status" group . Is this a bad idea or?

**Pull request merged**
