### PR TITLE
Add custom hostname and wifi LED indication

### PR DESCRIPTION
**Pull request by sveip**
Don't know if this is of interest, but it made my life a lot easier when I debugged the wifi-connection.

### CODE REVIEW

**Comment by jascdk** [comment]
@sveip Great - thanks alot for sharing your changes - i will merge it right away, and try it out on my own system. 

BTW i have had some thoughts on having some kind of setup option for all the different variables like mqtt server, username, wifi ssid and so on. 

For this i think tzapus wifimanager library is a good option. 

I have been looking into this code example for his library:

https://github.com/tzapu/WiFiManager/blob/master/examples/AutoConnectWithFSParameters/AutoConnectWithFSParameters.ino

I dont have great coding skills, but will give it a try to "merge" this library into this nilan code. 

What do you think about that?

**Comment by sveip** [comment]
I briefly looked at the library. What specifically do you want of additional "setup options"? It seems this library is great for a node that fails to connect to your Wifi AP, but I'm not sure if that is a big enough problem to justify adding that much complexity? 

From a user point of view, I can see that it might make the configuration file obsolete in total, so in that sense it will make "on-boarding" easier.

It looks like it's trivial to implement, so if you want to collaborate or that I should give it a go, I can try to find some time next week?

Vennlig hilsen,
Peter

**Comment by sveip** [comment]
BTW. what I would like to add, is more info to the root web-page. As of now I cant see any way to get any sensible data from the node if the serial isn't connected (correctly) to the Nilan. It would be great to have a landing page (index.html) that shows serial connectivity status etc. I'll open an issue on this, so that it's easier to track.

**Comment by jascdk** [comment]
@sveip Hi and thanks for quick reply:) My thoughts were to make it easier to configure. It is not a need to have but nice to have. The main thing it should do was to set it up for configuring ssid, ssid pass, mqtt port username and password, and maybe the "costum hostname" would be nice to configure through the librarys interface. It would indeed make onboarding much easier. It could then also be much easier for "non-arduino-people" to use.

Pre-compiled binaries for different esp board types could also be an option then.

Im very bad at coding , and would very much apreciate, if you would like to help with coding it - only if you want:)

To inspiration check out this : https://github.com/gysmo38/mitsubishi2MQTT

I use it myself and it has a setup like "tasmota" for ESP8266 units. It also has a page which shows status on connection etc. by using html pages :)

All the best

Jacob

**Pull request merged**
